/**
 * WindLog Master Terms of Service, EULA & Aviation Regulatory Safety Agreement
 * Version: 2026.1-REL
 */

export const CURRENT_LEGAL_VERSION = '2026.1-REL';

export interface LegalSection {
  id: string;
  title: string;
  content: string[];
  isCallout?: boolean;
  isUccCaps?: boolean;
}

export const LEGAL_DOCUMENT_TITLE = 'WINDLOG — AVIATION LEGAL DISCLAIMER, TERMS OF SERVICE & USER AGREEMENT';
export const LEGAL_DOCUMENT_SUBTITLE = 'Master End-User License Agreement (EULA), Aviation Regulatory Safety Notice & Privacy Statement';

export const LEGAL_SECTIONS: LegalSection[] = [
  {
    id: 'section-critical-notice',
    title: 'CRITICAL OPERATIONAL AVIATION NOTICE',
    isCallout: true,
    content: [
      'WindLog is strictly an auxiliary, non-certified educational, simulation, and situational awareness flight planning tool.',
      'WindLog is NOT an FAA/EASA certified navigation system (Non-TSO / Non-ETSO), NOT an authorized primary flight display, and NOT a Type B certified Electronic Flight Bag (EFB) for operational dispatch.',
      'The Software must NEVER be relied upon as the sole or primary means for aircraft navigation, terrain separation, airspace containment, minimum fuel calculations, or runway departure/landing authorization.',
    ],
  },
  {
    id: 'section-1-pic-authority',
    title: 'SECTION 1: PILOT-IN-COMMAND (PIC) NON-DELEGABLE RESPONSIBILITY',
    content: [
      '1.1 Sole and Absolute Operational Authority: Pursuant to International Civil Aviation Organization (ICAO) Annex 2 (Rules of the Air) and Annex 6 (Operation of Aircraft), European Union Aviation Safety Agency (EASA) Regulation (EU) No 965/2012 (Part-NCO.GEN.105, Part-NCC, Part-CAT), Federal Aviation Administration (FAA) 14 CFR § 91.3, UK Air Navigation Order (ANO), and all applicable National Aviation Authority (NAA) regulations, the Pilot-in-Command (PIC) is directly responsible for, and is the final authority as to, the safe and lawful operation of the aircraft.',
      '1.2 Mandatory Pre-Flight Action: In strict compliance with 14 CFR § 91.103, EASA NCO.OP.100, and equivalent international standards, the PIC is legally obligated to obtain and review all available official information concerning each intended flight prior to departure, including official meteorological briefings, NOTAMs, aeronautical charts, runway lengths, takeoff and landing distances, fuel requirements, and aircraft weight and balance.',
      '1.3 Non-Delegable Duty: Under no circumstances may any calculation, route waypoint vector, magnetic heading, runway crosswind advisory, or data presentation generated by WindLog relieve, diminish, or transfer the PIC\'s personal, non-delegable duty to verify all flight parameters using official, certified aeronautical publications and approved aircraft manuals.',
    ],
  },
  {
    id: 'section-2-non-certified-status',
    title: 'SECTION 2: NON-CERTIFIED ADVISORY STATUS & NO OPERATIONAL EFB CREDIT',
    content: [
      '2.1 Advisory and Educational Nature: WindLog is developed and distributed solely as a supplemental, informational, and pre-flight educational calculation aid.',
      '2.2 No Technical Standard Order (TSO) Authorization: The Software has not been evaluated, certified, or approved by the FAA under any Technical Standard Order (e.g. TSO-C157, TSO-C165), EASA under any ETSO, or national civil aviation authority.',
      '2.3 Non-Operational EFB Credit: WindLog is NOT an authorized Type B Electronic Flight Bag (EFB) software application for commercial air transport (CAT) or IFR operations under FAA AC 120-76D/E, FAA AC 91-78A, or EASA AMC 20-25. No operational credit may be claimed for pre-flight dispatch or in-flight navigation based solely upon calculations generated by this Software.',
      '2.4 Visual & Instrument Flight Cross-Checks: Pilots operating under VFR or IFR must maintain active visual lookout, terrain separation, and navigation cross-checks using certified onboard avionics, official VFR/IFR aeronautical sectional charts, and Air Traffic Control (ATC) clearances.',
    ],
  },
  {
    id: 'section-3-airspace-terrain',
    title: 'SECTION 3: AIRSPACE BOUNDARIES, TERRAIN & TEMPORARY FLIGHT RESTRICTIONS (TFRs)',
    content: [
      '3.1 Airspace Incursion Disclaimer: WindLog does NOT guarantee the real-time accuracy, vertical/horizontal containment, or active status of any controlled airspace (Class A, B, C, D, E), Special Use Airspace (Prohibited, Restricted, Danger, MOA, Alert Areas), Temporary Flight Restrictions (TFRs), Military Training Routes (MTRs/TRAs/TSAs), or NOTAM-activated airspace closures.',
      '3.2 Terrain and Obstacle Clearance: Topographical elevations, terrain contours, obstacle heights (antennas, wind turbines, power lines), and minimum sector altitudes (MSA/MORA/MEA) are advisory approximations only.',
      '3.3 Controlled Flight Into Terrain (CFIT): The PIC is solely responsible for maintaining terrain and obstacle separation. WindLog disclaims all liability for airspace infringements, regulatory enforcement actions, airspace violations, and Controlled Flight Into Terrain (CFIT).',
    ],
  },
  {
    id: 'section-4-weather-limitations',
    title: 'SECTION 4: METEOROLOGICAL DATA, METAR & WINDS ALOFT LIMITATIONS',
    content: [
      '4.1 Third-Party Data Sources: Meteorological data presented in WindLog—including METAR observations, surface winds, gusts, temperature, altimeter/QNH settings, and winds aloft—are retrieved via third-party APIs (including NOAA Aviation Weather Center and Open-Meteo ECMWF/GFS/ICON models).',
      '4.2 Latency and Micro-Scale Hazards: Meteorological data may be delayed, intermittent, estimated, interpolated, outdated, or unavailable. METAR reports reflect historical conditions at the time of observation and may not capture rapid atmospheric shifts, sudden wind shifts, microbursts, wind shear, thermal turbulence, localized mountain wave activity, icing, or convective cells.',
      '4.3 Official Meteorological Briefing Mandate: WindLog does NOT constitute an official weather briefing. Pilots are required to obtain official, standard meteorological briefings from certified State meteorological authorities (e.g., NAV Portugal / IPMA, FAA Flight Service / Leidos, DWD, Météo-France, AEMET) prior to engine start.',
    ],
  },
  {
    id: 'section-5-mass-balance-poh',
    title: 'SECTION 5: MASS & BALANCE, CG ENVELOPES & AIRCRAFT FLIGHT MANUAL (AFM/POH) SUPREMACY',
    content: [
      '5.1 Generic Model Profiles: Aircraft presets provided within WindLog (including Cessna 172, Piper PA-28, Tecnam P2002, Diamond DA40, and Rotax 912 profiles) are generic sample representations. Aircraft weights, empty weight arms, moment arms, fuel tank capacities, fuel arm locations, fuel density constants (Avgas, Mogas, Jet-A), baggage limits, and center-of-gravity (CG) envelope boundaries vary significantly between individual airframes, modifications, Supplemental Type Certificates (STCs), and tail registration numbers.',
      '5.2 POH / AFM Absolute Supremacy: The official Pilot\'s Operating Handbook (POH), Aircraft Flight Manual (AFM), and the current, certified Weight and Balance Report for the specific aircraft tail number being operated take absolute and indisputable precedence over any profile, default value, or calculation provided by WindLog.',
      '5.3 Zero Fuel, Takeoff, and Landing CG Verification: The pilot must independently confirm that the aircraft\'s actual loaded center of gravity and gross weight remain within approved manufacturer limits for all phases of flight (Takeoff, En-Route, and Landing), accounting for actual fuel burn and density variations.',
    ],
  },
  {
    id: 'section-6-fuel-reserves',
    title: 'SECTION 6: STATUTORY MINIMUM LEGAL FUEL RESERVES & USABLE FUEL',
    content: [
      '6.1 Indicative Fuel Computations: Any fuel endurance calculation, range estimation, or fuel burn rate presented in WindLog is purely mathematical and indicative.',
      '6.2 Usable vs. Unusable Fuel: The PIC remains strictly responsible for verifying actual onboard fuel quantities using calibrated visual/mechanical gauges and dipsticks, accounting for unusable fuel quantities specified in the AFM.',
      '6.3 Statutory Reserve Compliance: The PIC must ensure full compliance with statutory minimum legal reserve requirements (e.g., FAA 14 CFR § 91.151 for VFR Day +30m / Night +45m; 14 CFR § 91.167 for IFR; EASA Part-NCO.OP.125 / Part-CAT.OP.MPA.150 for contingency, alternate, and final reserve fuel). Never plan a flight without statutory reserve margins based on WindLog calculations.',
    ],
  },
  {
    id: 'section-7-runway-crosswind',
    title: 'SECTION 7: RUNWAY CROSSWIND, SURFACE CONTAMINATION (ICAO GRF) & DECLARED DISTANCES',
    content: [
      '7.1 Runway Alignments & Magnetic Variation: Aerodrome runway headings (QFU), lengths, elevations, and World Magnetic Model (WMM2025 epoch 2025–2030) declination values are compiled from open aeronautical databases and public AIS datasets. Physical runway modifications, displaced thresholds, surface contamination, airport construction, and runway closures (NOTAMs) may alter operational conditions.',
      '7.2 Advisory Crosswind Scoring: WindLog\'s crosswind calculations, component breakdowns, and "Recommended Runway" indicators are mathematical calculations based on reported wind vectors and geometric angles. They do not constitute an ATC clearance, operational directive, or guarantee of runway usability.',
      '7.3 ICAO GRF Contamination & Declared Distances (TORA/LDA): Crosswind calculations assume clean, dry pavement with standard braking action unless modified. They do NOT evaluate reduced friction coefficients (standing water, hydroplaning, snow, slush, ice) under the ICAO Global Reporting Format (GRF) or SNOWTAMs. Furthermore, calculations do not evaluate Runway Declared Distances (TORA, TODA, ASDA, LDA), runway gradient, or obstacle climb gradients. The PIC must calculate actual takeoff and landing ground roll using approved AFM performance charts.',
    ],
  },
  {
    id: 'section-8-cockpit-hardware',
    title: 'SECTION 8: COCKPIT HARDWARE, PWA STORAGE & MANDATORY BACKUP NAVIGATION',
    content: [
      '8.1 Consumer Hardware Environment: WindLog is a Progressive Web Application (PWA) operating on consumer-grade electronic hardware (tablets, smartphones, laptops). Consumer hardware is vulnerable to unexpected cockpit failure modes, including thermal shutdown from direct solar irradiance, rapid battery discharge, screen glare unreadability, operating system background process termination, GNSS/GPS signal loss, multipath interference, or browser cache/storage eviction.',
      '8.2 Mandatory Backup Requirements: Pilots must carry primary certified navigation instruments, current paper or certified secondary backup aeronautical charts, and certified backup flight planning documentation as required by applicable operational regulations (e.g., FAA AC 91-78A, EASA CS-EFB).',
    ],
  },
  {
    id: 'section-9-flight-instruction',
    title: 'SECTION 9: FLIGHT TRAINING, STUDENT PILOTS & INSTRUCTOR SUPERVISION',
    content: [
      '9.1 Student Pilot Operations: Student pilots operating under student pilot certificates or ab-initio training syllabi are expressly prohibited from utilizing WindLog as a basis for solo flight dispatch, cross-country planning, or mass-and-balance sign-offs without the direct prior review, verification, and written authorization of a certified Flight Instructor (CFI/FI/CRI).',
      '9.2 Instructor Supremacy: Nothing in this Software supersedes the training standards, operating limitations, or direct instructions established by the flight training organization (ATO/DTO) or the supervising flight instructor.',
    ],
  },
  {
    id: 'section-10-attributions',
    title: 'SECTION 10: THIRD-PARTY OPEN DATA & OPEN-SOURCE ATTRIBUTIONS',
    content: [
      '10.1 OpenStreetMap: Visual reporting points and geographic data derived from OpenStreetMap are licensed under the Open Database License (ODbL) v1.0 (© OpenStreetMap contributors).',
      '10.2 Open-Meteo: Meteorological weather forecast services are provided by Open-Meteo under the Creative Commons Attribution 4.0 International License (CC BY 4.0).',
      '10.3 NOAA / NCEI WMM2025: World Magnetic Model algorithms are developed by NOAA / NCEI and the British Geological Survey (BGS) and utilized in accordance with US public domain policies.',
      '10.4 SQLite / sql.js: Client-side database engines are powered by SQLite (Public Domain) and sql.js (MIT License).',
    ],
  },
  {
    id: 'section-11-privacy-local-storage',
    title: 'SECTION 11: CLIENT-SIDE LOCAL STORAGE & DATA PRIVACY (GDPR / CCPA / ePrivacy)',
    content: [
      '11.1 Local-First Architecture: WindLog operates on an offline-first, client-side compute model. Custom waypoints, aircraft profiles, scratchpad notes, fuel parameters, and Mass & Balance calculations are stored exclusively in the user\'s local browser memory (HTML5 LocalStorage and WebAssembly memory).',
      '11.2 Zero Remote Telemetry: WindLog does not collect, transmit, sell, or process personal flight plans or pilot identifiable data on remote servers.',
      '11.3 ePrivacy Directive Exemption: Pursuant to Article 5(3) of EU Directive 2002/58/EC (ePrivacy Directive), local device storage is utilized strictly for technical storage and user-initiated preferences necessary for the delivery of an explicitly requested service.',
      '11.4 Shareable Route URLs: If the user generates a shareable route link, route waypoints and performance profiles are serialized within the URL hash string. The user acknowledges that transmitting this URL discloses those flight parameters to the recipient.',
    ],
  },
  {
    id: 'section-12-ucc-warranty',
    title: 'SECTION 12: DISCLAIMER OF WARRANTIES (UCC § 2-316 MANDATORY CONSPICUOUS NOTICE)',
    isUccCaps: true,
    content: [
      '12.1 EXPRESS "AS IS" AND "AS AVAILABLE" DISCLAIMER:',
      'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE, DATA, CALCULATIONS, WAYPOINT DIRECTORIES, WINDS ALOFT ESTIMATES, MASS & BALANCE ENVELOPES, AND RUNWAY WIND COMPUTATIONS ARE PROVIDED STRICTLY ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITH ALL FAULTS AND DEFECTS.',
      '12.2 STATUTORY UCC DISCLAIMER:',
      'THE CREATORS, CONTRIBUTORS, DEVELOPERS, AND DISTRIBUTORS OF WINDLOG SPECIFICALLY AND EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO: (A) ANY IMPLIED WARRANTY OF MERCHANTABILITY; (B) ANY IMPLIED WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE OR AIRWORTHINESS; (C) ANY WARRANTY OF TITLE, QUIET ENJOYMENT, OR NON-INFRINGEMENT; AND (D) ANY WARRANTY ARISING FROM COURSE OF DEALING, USAGE, OR TRADE PRACTICE.',
      '12.3 NO GUARANTEE OF CONTINUOUS ACCURACY OR AVAILABILITY:',
      'NO ORAL OR WRITTEN ADVICE, SIMULATION RESULT, OR INFORMATION PROVIDED BY WINDLOG SHALL CREATE ANY WARRANTY. WINDLOG DOES NOT WARRANT THAT THE SOFTWARE WILL OPERATE UNINTERRUPTED, ERROR-FREE, BUG-FREE, OR COMPATIBLE WITH ANY SPECIFIC BROWSER, OPERATING SYSTEM, OR HARDWARE PLATFORM.',
    ],
  },
  {
    id: 'section-13-limitation-liability',
    title: 'SECTION 13: STRICT LIMITATION OF LIABILITY & DAMAGES CAP (WITH EU/UK SAVINGS CLAUSE)',
    isUccCaps: true,
    content: [
      '13.1 WAIVER OF CONSEQUENTIAL, INDIRECT, AND AVIATION-RELATED DAMAGES:',
      'TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, IN NO EVENT SHALL THE CREATORS, DEVELOPERS, CONTRIBUTORS, LICENSORS, OR MAINTAINERS OF WINDLOG BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING WITHOUT LIMITATION: (A) LOSS OF AIRCRAFT HULL, AIRFRAME DAMAGE, OR AVIONICS FAILURE; (B) AIRSPACE INFRINGEMENTS, REGULATORY CITATIONS, PILOT CERTIFICATE SUSPENSIONS, OR FINES; (C) OPERATIONAL DELAYS, FUEL EXHAUSTION, CONTROLLED FLIGHT INTO TERRAIN (CFIT), OFF-AIRPORT FORCED LANDINGS, RUNWAY EXCURSIONS, LOSS OF CONTROL, OR FLIGHT INCIDENTS; (D) LOSS OF PROFITS, LOSS OF REVENUE, OR LOSS OF FLIGHT LOG DATA; OR (E) PERSONAL INJURY, BODILY HARM, WRONGFUL DEATH, OR PSYCHOLOGICAL TRAUMA ARISING OUT OF, RELATED TO, OR RESULTING FROM THE USE OF, MISUSE OF, INABILITY TO USE, OR RELIANCE UPON WINDLOG, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE), EVEN IF INFORMED OF THE POSSIBILITY OF SUCH DAMAGES.',
      '13.2 AGGREGATE MONETARY LIABILITY CAP:',
      'IN JURISDICTIONS WHERE LIABILITY CANNOT BE FULLY DISCLAIMED BY LAW, THE TOTAL AGGREGATE LIABILITY OF THE DEVELOPERS AND CONTRIBUTORS FOR ALL CLAIMS OF ANY KIND ARISING UNDER OR RELATED TO THIS AGREEMENT OR THE SOFTWARE SHALL BE STRICTLY CAPPED AT AND NOT EXCEED THE TOTAL AMOUNT ACTUALLY PAID BY YOU TO WINDLOG FOR ACCESS TO THE SOFTWARE IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR FIFTY UNITED STATES DOLLARS ($50.00 USD / £50.00 GBP / €50.00 EUR), WHICHEVER IS LESS.',
      '13.3 MANDATORY STATUTORY SAVINGS CLAUSE (UK CONSUMER RIGHTS ACT & EU DIRECTIVE 93/13/EEC):',
      'Nothing in this Agreement shall operate to exclude or limit liability that cannot be excluded or limited under mandatory applicable consumer protection laws, including Section 65(1) of the UK Consumer Rights Act 2015 (liability for death or personal injury resulting from trader negligence), national implementations of EU Directive 93/13/EEC, or liability for intentional wrongdoing (Vorsatz) or gross negligence (grobe Fahrlässigkeit) under mandatory civil codes.',
    ],
  },
  {
    id: 'section-14-governing-law',
    title: 'SECTION 14: INDEMNIFICATION, GOVERNING LAW, FORUM SELECTION & SEVERABILITY',
    content: [
      '14.1 User Indemnification: You agree to defend, indemnify, and hold harmless the creators, developers, maintainers, contributors, and hosting providers of WindLog from and against any and all claims, liabilities, losses, damages, fines, regulatory penalties, judgments, costs, and expenses (including reasonable attorneys\' fees) arising out of or related to: (a) your operation, piloting, navigation, or flight planning of any aircraft; (b) any breach by you of this Agreement or applicable Federal Aviation Regulations (FARs), EASA rules, or national airspace laws; (c) your reliance upon any calculations, winds aloft, waypoint coordinates, or mass & balance diagrams generated by the Software; or (d) any third-party claim, passenger claim, wrongful death claim, or property damage claim resulting from a flight planned with WindLog.',
      '14.2 Governing Law & Forum Selection: This Agreement shall be governed by and construed in accordance with the substantive laws of the State of Delaware, United States, without giving effect to any conflict of law principles. Any legal suit, action, or proceeding arising out of or related to this Agreement shall be instituted exclusively in the courts located in Delaware.',
      '14.3 Class Action Waiver: TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, ALL CLAIMS MUST BE BROUGHT IN THE USER\'S INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE, CONSOLIDATED, OR REPRESENTATIVE PROCEEDING.',
      '14.4 Severability & Entire Agreement: If any provision of this Agreement is held to be invalid, illegal, or unenforceable, the validity, legality, and enforceability of the remaining provisions shall not in any way be affected or impaired thereby. This Agreement constitutes the complete and exclusive understanding between the user and WindLog regarding the Software.',
    ],
  },
];
